export const paletteVariables = {
  '--foreground': '255,255,255',
  '--foreground-strong': '0,0,0',
  '--grey': '211,211,211',
  '--primary': '252,68,140',
  '--secondary': '255,78,43',
  '--tertiary': '165,125,250',
  '--elevation': '0,0,0',
  '--white': '255,255,255',
  '--light': '250,250,250',
  '--positive': '46, 204, 113',
  '--negative': '255, 76, 48',
  '--background-overlay': '193, 198, 207',
};

export const lineWidthVariables = {
  '--spacing-0': '0px',
  '--spacing-0.5': '0.5px',
  '--spacing-1': '1px',
  '--spacing-2': '2px',
  '--spacing-3': '3px',
  '--spacing-4': '5px',
  '--spacing-5': '5px',
  '--spacing-6': '6px',
  '--spacing-7': '7px',
  '--spacing-8': '8px',
  '--spacing-9': '9px',
  '--spacing-10': '10px',
};

export const spacingVariables = {
  '--spacing-0': '0px',
  '--spacing-0.5': '4px',
  '--spacing-1': '8px',
  '--spacing-2': '16px',
  '--spacing-3': '24px',
  '--spacing-4': '32px',
  '--spacing-5': '40px',
  '--spacing-6': '48px',
  '--spacing-7': '56px',
  '--spacing-8': '64px',
  '--spacing-9': '72px',
  '--spacing-10': '80px',
};

export const borderRadiusVariables = {
  '--none': '0px',
  '--radius-standard': '4px',
  '--radius-input': '6px',
  '--radius-round': '100px',
};

export const typographyVariables = {
  '--text-subtitle-font-size': '12px',
  '--text-subtitle-line-height': '12px',
  '--text-subtitle-font-weight': '500',
  '--text-subtitle-font-family': 'var(--font-primary)',
  '--textbody-font-size': '16px',
  '--textbody-line-height': '24px',
  '--textbody-font-weight': '400',
  '--textbody-font-family': 'var(--font-primary)',
  '--text-title1-font-size': '64px',
  '--text-title1-line-height': '72px',
  '--text-title1-font-weight': '500',
  '--text-title1-font-family': 'var(--font-primary)',
  '--text-title2-font-size': '56px',
  '--text-title2-line-height': '64px',
  '--text-title2-font-weight': '400',
  '--text-title2-font-family': 'var(--font-primary)',
  '--text-title3-font-size': '48px',
  '--text-title3-line-height': '56px',
  '--text-title3-font-weight': '300',
  '--text-title3-font-family': 'var(--font-primary)',
  '--text-title4-font-size': '40px',
  '--text-title4-line-height': '48px',
  '--text-title4-font-weight': '300',
  '--text-title4-font-family': 'var(--font-primary)',
  '--text-headline-font-size': '24px',
  '--text-headline-line-height': '32px',
  '--text-headline-font-weight': '500',
  '--text-headline-font-family': 'var(--font-primary)',
};
