import {
  RiHome6Line,
  RiPulseFill,
  RiImage2Line,
  RiCloseLine,
  RiSettings5Line,
  RiTimeLine,
  RiUser3Line,
  RiMapPin2Line,
  RiHeartLine,
  RiSearchLine,
  RiChat3Line,
  RiCheckLine,
  RiSendPlaneLine,
  RiFlag2Line,
  RiFlashlightLine,
  RiImageLine,
  RiTwitterLine,
  RiInstagramLine,
  RiAddCircleLine,
  RiEditBoxFill,
  RiLogoutBoxFill,
  RiLockFill,
  RiUserFollowFill,
  RiShieldUserFill,
  RiMoreFill,
  RiArrowDownCircleLine,
} from 'react-icons/ri';

import { BiDownArrow, BiUpArrow, BiSliderAlt } from 'react-icons/bi';

import { MdOutlineAddReaction } from 'react-icons/md';

export const icons = {
  BiDownArrow,
  BiUpArrow,
  BiSliderAlt,
  RiHome6Line,
  RiSearchLine,
  RiPulseFill,
  RiUser3Line,
  RiImage2Line,
  RiCloseLine,
  RiSettings5Line,
  RiTimeLine,
  RiMapPin2Line,
  RiHeartLine,
  RiChat3Line,
  RiCheckLine,
  RiSendPlaneLine,
  RiFlag2Line,
  RiFlashlightLine,
  MdOutlineAddReaction,
  RiImageLine,
  RiTwitterLine,
  RiInstagramLine,
  RiAddCircleLine,
  RiEditBoxFill,
  RiLogoutBoxFill,
  RiLockFill,
  RiUserFollowFill,
  RiShieldUserFill,
  RiMoreFill,
  RiArrowDownCircleLine,
};
